### ISSUE TITLE
Track route fails if server doesn't require a password

### ISSUE THREAD

**Issue by kevcenteno** [node-freight/freight-server#19]
At https://github.com/node-freight/freight-server/blob/master/routes/freight.js#L93, there's a check for `req.body.password`, and this will return `falsy` if `req.body.password` is an empty string.

**Comment by vladikoff** [comment]
Closed via https://github.com/node-freight/freight-server/pull/20#issuecomment-156592326 
This is by design. Will reopen if needed

**Comment by kevcenteno** [comment]
If the user explicitly sets no password in their config, then we should honour that setting

**Comment by vladikoff** [comment]
> If the user explicitly sets no password in their config, then we should honour that setting

Got it, filed https://github.com/node-freight/freight-server/issues/21
I will need to do a few more changes (more than PR 20)
